// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANllP9Wl9RcmkEQB3HPRvMB7ofccHWPm8',
    appId: '1:507153465962:android:d2963ae603d2e581040013',
    messagingSenderId: '507153465962',
    projectId: 'flutter-tdd-sample',
    storageBucket: 'flutter-tdd-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcd5SnAUrXnYWxRICslzDE5j7AiiDw_0',
    appId: '1:507153465962:ios:aa4f61f6088a6bfe040013',
    messagingSenderId: '507153465962',
    projectId: 'flutter-tdd-sample',
    storageBucket: 'flutter-tdd-sample.appspot.com',
    iosClientId: '507153465962-0g5d2t3asma5ii5345u0ic0elcnsomep.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTddSample',
  );
}
